### ISSUE TITLE
Using DrawUserPrimitives with Xelmish

### ISSUE THREAD

**Issue by AlexanderLindsay** [ChrisPritchard/Xelmish#10]
I am not that familiar with Monogame so its possible that there are better ways to do this, but I wanted to draw a hex grid and so needed to use `DrawUserPrimitives`. I was able to do this without making changes to Xelmish by making getting the `GraphicsDevice` out of the `SpriteBatch` and changing some settings on the `graphicsDevice` and `basicEffect`, like so:

```
        let graphicsDevice = spriteBatch.graphicsDevice
        let basicEffect = new BasicEffect(graphicsDevice)

        graphicsDevice.RasterizerState <- RasterizerState.CullCounterClockwise
        graphicsDevice.DepthStencilState <- DepthStencilState.Default;
        basicEffect.World <- Matrix.CreateOrthographicOffCenter(0f, float32 graphicsDevice.Viewport.Width, float32 graphicsDevice.Viewport.Height, 0f, 0f, 1f);
        basicEffect.VertexColorEnabled <- true;

        let centers =
            grid.Hexes
            |> Map.toList
            |> List.map (fun (coor, hex) -> (coor, hexToPixel grid.Orientiation grid.Size grid.Offset hex.Coor))
        
        basicEffect.CurrentTechnique.Passes 
            |> List.ofSeq
            |> List.iter (fun pass -> 
                pass.Apply()
                centers
                |> List.iter (fun (_, (cx, cy)) -> 
                    let points = hexToPoints (cx, cy) { X = grid.Size.X - 2.; Y = grid.Size.Y - 2. }
                    let hexVerts = 
                        points
                        |> List.map (fun (x, y) -> VertexPositionColor(Position = vector3 (float32 x) (float32 y) 0f, Color = Color.Red))
                        |> List.toArray
                    
                    let outlinePoints = hexToPoints (cx, cy) grid.Size
                    let outlineVerts =
                        outlinePoints
                        |> List.map (fun (x, y) -> VertexPositionColor(Position = vector3 (float32 x) (float32 y) 0f, Color = Color.Black))
                        |> List.toArray

                    graphicsDevice.DrawUserPrimitives(PrimitiveType.TriangleList, outlineVerts, 0, 6) 
                    graphicsDevice.DrawUserPrimitives(PrimitiveType.TriangleList, hexVerts, 0, 6) 
                )
            )
        spriteBatch.End() \\end the Xelmish sprite batch
        spriteBatch.Begin(SpriteSortMode.Immediate) \\start another sprite batch
        let font = loadedAssets.fonts.["basic"]
        centers
            |> List.iter (fun (coor, (cx, cy)) -> 
                let coorString = sprintf "(%i, %i)" coor.Q coor.R
                let measure = font.MeasureString(coorString)
                let tx = float32 cx - measure.X / 2f
                let ty = float32 cy - measure.Y / 2f
                spriteBatch.DrawString(font, coorString, vector2 tx ty, Colour.White)
            )
        \\leave the sprite batch unended so that Xelmish can end it
```

This works, but it seemed like maybe not the best approach, so I created my own GameLoop class and used a slightly different Draw and Viewables definition:

```
type GraphicsDevice = Microsoft.Xna.Framework.Graphics.GraphicsDevice

type BatchSetup = (LoadedAssets -> Inputs -> GraphicsDevice -> SpriteBatch -> unit)
type BatchContent = (LoadedAssets -> Inputs -> GraphicsDevice -> SpriteBatch -> unit) list
type BatchCleanup = (LoadedAssets -> Inputs -> GraphicsDevice -> SpriteBatch -> unit)

type Drawable = 
    | Sprite of (LoadedAssets -> Inputs -> SpriteBatch -> unit)
    | Graphic of (LoadedAssets -> Inputs -> GraphicsDevice -> unit)
    | Both of (LoadedAssets -> Inputs -> GraphicsDevice -> SpriteBatch -> unit)
    | Batch of BatchSetup*BatchContent*BatchCleanup

type ViewableGraphics = 
    | OnDraw of Drawable
    | OnUpdate of (Inputs -> unit
```

```
    override __.Draw gameTime =
        Option.iter this.GraphicsDevice.Clear config.clearColour

        let graphicsDevice = this.GraphicsDevice

        drawables
        |> List.iter (fun drawable ->
            match drawable with
            | Sprite df ->
                spriteBatch.Begin (sortMode = SpriteSortMode.Immediate)
                df assets inputs spriteBatch
                spriteBatch.End ()
            | Graphic df ->
                df assets inputs graphicsDevice
            | Both df ->
                df assets inputs graphicsDevice spriteBatch
            | Batch (setup,content,cleanup) ->
                setup assets inputs graphicsDevice spriteBatch
                content
                |> List.iter (fun df -> df assets inputs graphicsDevice spriteBatch)
                cleanup assets inputs graphicsDevice spriteBatch
        )
```

Since the Xelmish GameLoop class is marked as internal I couldn't base my GameLoop class off of it so it has to re implement a lot of the work that occurs in GameLoop . That is one possible change, make GameLoop not internal to better support this type of thing.

Not sure if the rest of it really fits in Xelmish but I wanted to surface it in case there is some changes I should make into a PR. I don't think they fit exactly as I have them now, but maybe some variant is worthwhile.

If nothing else, now if anyone else is looking to use `DrawUserPrimitives` with Xelmish they can reference this.

**Comment by ChrisPritchard** [comment]
I feel like this bit is likely inefficient:

```
        drawables
        |> List.iter (fun drawable ->
            match drawable with
            | Sprite df ->
                spriteBatch.Begin (sortMode = SpriteSortMode.Immediate)
                df assets inputs spriteBatch
                spriteBatch.End ()
```

If you have a hundred sprites would it not start and stop the batch a 100 times?

In any event, good work! But vertex-based drawing, user primitives etc is slightly outside my vision for Xelmish, as it would allow 3D models etc. I feel like supporting it and all the custom configuration would be just easier with a raw monogame project than through Xelmish's abstractions. But I will see about making it not internal (maybe breaking out some of the steps of draw/update so they can be overwritten, etc).

When I draw hex grids with it, I just use a sprite for each hex and draw that just like with other sprites. You could give that a try, or stick with your approach which looks neat :)

**Comment by AlexanderLindsay** [comment]
Yeah that is a good point about it being inefficient. I added the batch type to try and account for that sort of thing but that has a bit more overhead, so its a trade off. 

I will probably need to either add or replace this with texture drawing at some point but I did it this way to understand the hex stuff a bit better. (I had tried it with textures first but it wasn't working, turned out I had a bug with the hex to pixel function but I didn't find that until after I switched)

Thanks for taking a look at this and for making Xelmish in the first place, its pretty cool!

**Comment by ChrisPritchard** [comment]
You might find the tutorials by catlike coding interesting: https://catlikecoding.com/unity/tutorials/hex-map/ Its in unity, and c# (I did a full implementation of it [here](https://github.com/ChrisPritchard/HexMapTutorials)) but its also entirely vertex based, so *in theory* could be done in Monogame. 

Or, if you wanted to use Unity but stick with F#, I did a small project on doing F# with unity [here](https://github.com/ChrisPritchard/2d-games-with-unity-in-fsharp) that has some setup/process instructions that might be useful.
