### ISSUE TITLE
Cross Platform Support?

### ISSUE THREAD

**Issue by RickyYCheng** [ChrisPritchard/Xelmish#11]
I found that the xelmish was written by MonoGame.DesktopGL. 
When writing multi-platform game(such as UWP, desktopgl, or windowsdx), how should I share the core loop in xelmish? 
Can any1 write an example?

**Comment by ChrisPritchard** [comment]
Do you mean how would you use something other than monogame? I think you would need to create your own version of the GameLoop class, with the draw methods rewritten for the different framework. Xelmish is pretty tied to monogame.

**Comment by ChrisPritchard** [comment]
Or am I misunderstanding? Might bump this to .NET 6 soon too.

**Comment by RickyYCheng** [comment]
> Do you mean how would you use something other than monogame? I think you would need to create your own version of the GameLoop class, with the draw methods rewritten for the different framework. Xelmish is pretty tied to monogame.

Hi Chris!
In monogame C#, we can choose platforms like gl, dx, uwp, even linux or something more. 
In C#, the best way to achieve that is to write a `monogame shared project`, and different platform projects. 
So I just want to use monogame things, but different game platforms. 

I'm wondering that how to achieve this in F# and xelmish, because the `shared project template` is only for C#. 
Can we consider the xelmish a platform independent library? 
Or can we write only one core project and run it on different platforms?

**Comment by ChrisPritchard** [comment]
Hmm, I'll take a look. If its doable in C# there will be a way to do it in F#, especially with the Xelmish core library since the gameloop is largely a C# class in F# syntax.

**Comment by RickyYCheng** [comment]
> Hmm, I'll take a look. If its doable in C# there will be a way to do it in F#, especially with the Xelmish core library since the gameloop is largely a C# class in F# syntax.

I use a project to reference my F# project, and do something like this 
```fs
let run () = 
        Program.mkProgram init update view
        |> Xelmish.Program.runGameLoop config
```
> in my xelmish module
```cs
Program.App.run();
```
> c# code (from a specific platform template)

and got a null reference exception.

**Comment by ChrisPritchard** [comment]
What was the platform template you used, so I can try and replicate?

**Comment by RickyYCheng** [comment]
> What was the platform template you used, so I can try and replicate?

I choose windows dx to make a difference(but desktop gl will show the same matter)

**Comment by ChrisPritchard** [comment]
Are you using the nuget package or building the project your self from source?

I've upgraded to MonoGame 3.8, and added a 'PrivateAssets All' to the core Xelmish project, which basically makes it a portable library (the old way has been deprecated). I then tested this with a new sample project using windowsdx, as well as the other gl projects and its looking good.

I've pushed this all up into this branch: https://github.com/ChrisPritchard/Xelmish/tree/monogame-3.8-portable

**Comment by RickyYCheng** [comment]
> Are you using the nuget package or building the project your self from source?

Use both nuget and my forked project before. 

> I've pushed this all up into this branch: https://github.com/ChrisPritchard/Xelmish/tree/monogame-3.8-portable

I'll try the new branch.

**Comment by RickyYCheng** [comment]
> Are you using the nuget package or building the project your self from source?
> 
> I've upgraded to MonoGame 3.8, and added a 'PrivateAssets All' to the core Xelmish project, which basically makes it a portable library (the old way has been deprecated). I then tested this with a new sample project using windowsdx, as well as the other gl projects and its looking good.
> 
> I've pushed this all up into this branch: https://github.com/ChrisPritchard/Xelmish/tree/monogame-3.8-portable

windws dx works well.  :) 
I use both your F# dx project and a C# dx project which references the F# project. 

Is it possible to make a uwp version? 
There're lots of problems. 

1. uwp version use factory 
```cs
var factory = new MonoGame.Framework.GameFrameworkViewSource<Game1>();
Windows.ApplicationModel.Core.CoreApplication.Run(factory);
```
2. uwp can only reference net standard, which means xelmish and F# project which uwp need to use should be net standard. 
(the project seems like this:
Xelmish source <- F# application (library) <- specific monogame template, 
so we can share our F# application)

**Comment by ChrisPritchard** [comment]
Ok, Ill take a look.

**Comment by RickyYCheng** [comment]
The reason I choose to use the C# project to start up the game is that in monogame C# project template has almost everything we need. 

For example, in the sample `space invader clone`, there's a monogame problem. 
In my pc(Windows 11), the dpi scaling is set to be 125%, such that the game graphics is wired. 

Since the project has no `app.manifest` file, the project will not enable "dpi awareness"(usually in C# project template there's always a manifest file and always enable "dpi awareness"(ignore dpi scaling)). 

I think the F# project should be the library.

**Comment by ChrisPritchard** [comment]
Ok. I looked into UWP and I dont think thats going to happen: Xelmish is all .NET 5 now, and I dont really want to down grade it (might even upgrade it soon to NET 6). UWP looks like its being deprecated in lieu of the new windows app sdk / direct x stuff: https://visualstudiomagazine.com/articles/2021/10/19/uwp-migration.aspx

However, I was able to add an app manifest to the direct x sample project and reference it in the project file, and it looks like it works as expected - I tested on my win 11 laptop which has high DPI.

**Comment by RickyYCheng** [comment]
> However, I was able to add an app manifest to the direct x sample project and reference it in the project file, and it looks like it works as expected - I tested on my win 11 laptop which has high DPI.

That's what I've done. 
And is it possible to add manifest file to xelmish instead of game app? 

> Ok. I looked into UWP and I dont think thats going to happen: Xelmish is all .NET 5 now, and I dont really want to down grade it (might even upgrade it soon to NET 6). UWP looks like its being deprecated in lieu of the new windows app sdk / direct x stuff: https://visualstudiomagazine.com/articles/2021/10/19/uwp-migration.aspx

agree.

**Comment by RickyYCheng** [comment]
I changed the target framework to net6.0 in my forked xelmish project. 
I donnot know where's the difference between net5.0 xelmish and net6.0 xelmish. 
Seems like everything is the same.

**Comment by ChrisPritchard** [comment]
> I changed the target framework to net6.0 in my forked xelmish project. I donnot know where's the difference between net5.0 xelmish and net6.0 xelmish. Seems like everything is the same.

Sure. But monogame 3.8 only officially sticks with net 5, so I'll probably hold off in case there are some platform compatibility problems I can't test.

> And is it possible to add manifest file to xelmish instead of game app?

Unfortunately that doesnt work - it has to be per project. I tested it with tetris clone and its fine, and then I built that on linux and tested it and while it didnt work there, it didnt break the build so thats fine too.

I can produce a nuget package if you are happy.

**Comment by RickyYCheng** [comment]
> Unfortunately that doesnt work - it has to be per project. I tested it with tetris clone and its fine, and then I built that on linux and tested it and while it didnt work there, it didnt break the build so thats fine too.

manifest file only ignores the dpi problem on windows. 
```xml
<application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/pm</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">permonitorv2,permonitor</dpiAwareness>
    </windowsSettings>
  </application>
```
maybe there're other platforms' settings. 
decide to monogame team. 

> I can produce a nuget package if you are happy.

If it is good enough i think this should be a good idea. 
(by the way, i almost only work on my xelmish forked project, instead of nuget) :)

**Comment by RickyYCheng** [comment]
I'll close the issue. 
Since everything's fine.

**Comment by ChrisPritchard** [comment]
Will merge in now. Thanks!
