### ISSUE TITLE
[Question] Accessing the Game-object

### ISSUE THREAD

**Issue by b0wter** [ChrisPritchard/Xelmish#20]
I'd like to access the MonoGame `Game`-object, e.g. for retrieving the `Content`-folder.
Is this not meant to be done? Or is Xelmish just minimalistic in its approach and meant to be extended by its user?

**Comment by ChrisPritchard** [comment]
Xelmish just tries to allow you to build a pure Elm-like wrapper on top of MonoGame, which is why it appears restricted. If you need to break that model to access something in MonoGame go ahead.

**Comment by b0wter** [comment]
Thanks for the info! I found that instead of adding Xelmish by nuget adding the code directly allowed me to better understand how things work and make some minor adjustments (like adding a new content type for `LoadedAssets`) to get things going for me while keeping the model intact :)

I have no experience with MonoGame or Elmish (but Elm) so I was curious if I was missing something obvious.
