### ISSUE TITLE
Blank project

### ISSUE THREAD

**Issue by reigam** [ChrisPritchard/Xelmish#8]
What would be the best way to start a blank project in VS 2019?
- create an empty console app, add nuget package and modify?
- use the monogame c# templates and go from there?
- just use the sample app from the repository?

Thanks

**Comment by ChrisPritchard** [comment]
Hi! I'd probably just use one of the sample apps, as they're stripped back to whats absolutely necessary. One thing is that they have dependencies on the main xelmish project, NOT the nuget package, so you would either want to remove that reference and add the nuget package, or include xelmish itself with your project.

The latter isn't too bad an option: its only a very small amount of files, and has largely been built to my needs - you might find that there are things you want to change as you go, and having the (quite well commented) code handy might be more flexible than trying to get me to modify it and build another nuget package.

**Comment by reigam** [comment]
Thanks for the fast answer. 
I was very happy to see Xelmish getting an update, great work!
